[package]
name = "warehouse_management"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0", features = ["io"] }
axum = { version = "0", features = ["http1", "http2", "form", "tokio"], default-features = false }
axum-extra = { version = "0", features = ["cookie"], default-features = false }
tower = { version = "0", features = ["limit"] }
tower-http = { version = "0", features = ["timeout", "compression-full", "trace"] }
serde = { version = "1", features = ["derive"], default-features = false }
mime_guess = "2"
sqlx = { version = "0", features = ["runtime-tokio", "postgres", "time"], default-features = false }
argon2 = { version = "^0.6.0-rc.7" }
rand = { version = "0", features = ["std_rng", "sys_rng"], default-features = false }
base16ct = { version = "1", features = ["alloc"], default-features = false }
email_address = { version = "0", default-features = false }
time = { version = "0", features = ["serde"], default-features = false }
tracing-subscriber = { version = "0", features = ["std", "fmt"], default-features = false }
tracing = { version = "0", default-features = false }
sanitize-filename = "0"

[profile.release]
strip = "symbols"
panic = "abort"
opt-level = 3
codegen-units = 1